### ISSUE TITLE
bigger than life

### ISSUE THREAD

**Issue by RobinTPotter** [hancoro/Python_Learn_Project#1]
#use headless option to make your screen massive

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--headless")

driver = webdriver.Chrome(options=options, executable_path='c:/xxx/chromedriver.exe')
driver.get('https://robintpotter.github.io/its-pages-all-the-way-down/svg/uno_cards.svg?page=8')
driver.set_page_load_timeout(10)
driver.set_window_size(4000,4000)
driver.get_screenshot_as_file('poo.png')

**Comment by hancoro** [comment]
I consider this code I have seen.
